name: phonescannerapp
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=2.19.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  device_info_plus: ^9.0.0 # Reemplaza con la última versión disponible
  http: ^0.13.3
  flutter_dotenv: ^5.0.2
  provider: ^6.0.0
  google_generative_ai: ^0.0.1-dev
  connectivity_plus: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - .env
    - assets/logo.png
    - assets/recomendations.json
  uses-material-design: true
